---
title: "NYTS 2016 Cleaning - Ishika"
format: html
editor: visual
---

```{r library}
library(dplyr)
library(readxl)
library(ggplot2)
library(readr)
```

```{r setup}
getwd()
YTSData2016csv <- read_excel('C:/Users/ishik_o/OneDrive/Desktop/r_projects/YTS16_18_21/nyts2016.xlsx')
```

```{r renamecol}
#first select columns to keep
YTSData2016 <- YTSData2016csv %>% 
  select("Q2","Q3","Q26","Q31","Q25","Q27","Q28","Q7","Q13","Q26","Q6","Q7","Q82","Q55","Q73","Q74") 

YTSData2016 <- YTSData2016csv %>%
  rename(
    Gender <- Q2,
    Grade_of_Student <- Q3,
    E_Cig_Ever_Used <- Q26,
    E_Cig_Days_Used <- Q31,
    E_Cig_Curiousity <- Q25,
    E_Cig_Try <- Q27,
    E_Cig_Try_Next_Year <- Q28,
    Cigarette_Ever_Used <- Q7,
    Cigarette_Days_Used <- Q13,
    Cigarette_Last_Used <- Q26,
    Cigarette_Curiosity <- Q6,
    Cigarette_Try <- Q7,
    The_Real_Cost <- Q82,
    Any_Tobacco_Craving <- Q55,
    `E-Cig_Promotions_Internet` <- Q73,
    `Tobacco_Promotions_Internet` <- Q74
  )
```

```{r Duplicating and saving new dataset}
YTSData2016Numbers <- YTSData2016
write.csv(YTSData2016Numbers, file = "NYTS2016DataNumbers.csv")
```

```{r clean values}
# Q2
YTSData2016$Gender <- as.character(YTSD2016$Gender)

YTSData2016$Gender[YTSData$Gender == "1"] <- "M"
YTSData2016$Gender[YTSData$Gender == "2"] <- "F"

# Q3
YTSData2016$Grade_of_Student <- as.character(YTSData2016$Grade_of_Student)
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "1"] <- "6th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "2"] <- "7th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "3"] <- "8th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "4"] <- "9th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "5"] <- "10th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "6"] <- "11th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "7"] <- "12th"
YTSData2016$Grade_of_Student[YTSData2016$Grade_of_Student == "8"] <- "Unplaced"

# Q26
YTSData2016$E_Cig_Ever_Used <- as.character(YTSData2016$E_Cig_Ever_Used)
YTSData2016$E_Cig_Ever_Used[YTSData2016$E_Cig_Ever_Used == "1"] <- "Yes"
YTSData2016$E_Cig_Ever_Used[YTSData2016$E_Cig_Ever_Used == "2"] <- "No"

# Q31 Maybe change values in future they seem to be good
YTSData2016$E_Cig_Days_Used <- as.character(YTSData2016$E_Cig_Days_Used)
YTSData2016$E_Cig_Days_Used[YTSData2016$E_Cig_Days_Used == "1"] <- "1"
YTSData2016$E_Cig_Days_Used[YTSData2016$E_Cig_Days_Used == "2"] <- "5"
YTSData2016$E_Cig_Days_Used[YTSData2016$E_Cig_Days_Used == "3"] <- "15"
YTSData2016$E_Cig_Days_Used[YTSData2016$E_Cig_Days_Used == "4"] <- "35"
YTSData2016$E_Cig_Days_Used[YTSData2016$E_Cig_Days_Used == "5"] <- "75"
YTSData2016$E_Cig_Days_Used[YTSData2016$E_Cig_Days_Used == "6"] <- "100"

# Q25
YTSData2016$E_Cig_Curiousity <- as.character(YTSData2016$E_Cig_Curiousity)

YTSData2016$E_Cig_Curiousity[YTSData2016$E_Cig_Curiousity == "1"] <- "Yes"
YTSData2016$E_Cig_Curiousity[YTSData2016$E_Cig_Curiousity == "2"] <- "Yes"
YTSData2016$E_Cig_Curiousity[YTSData2016$E_Cig_Curiousity == "3"] <- "No"
YTSData2016$E_Cig_Curiousity[YTSData2016$E_Cig_Curiousity == "4"] <- "No"

#Q26
YTSData2016$E_Cig_Try <- as.character(YTSData2016$E_Cig_Try)
YTSData2016$E_Cig_Try[YTSData2016$E_Cig_Try == "1"] <- "Yes"
YTSData2016$E_Cig_Try[YTSData2016$E_Cig_Try == "2"] <- "Yes"
YTSData2016$E_Cig_Try[YTSData2016$E_Cig_Try == "3"] <- "No"
YTSData2016$E_Cig_Try[YTSData2016$E_Cig_Try == "4"] <- "No"

# Q28
YTSData2016$E_Cig_Try_Next_Year <- as.character(YTSData2016$E_Cig_Try_Next_Year)
YTSData2016$E_Cig_Try_Next_Year[YTSData2016$E_Cig_Try_Next_Year == "1"] <- "Yes"
YTSData2016$E_Cig_Try_Next_Year[YTSData2016$E_Cig_Try_Next_Year == "2"] <- "Yes"
YTSData2016$E_Cig_Try_Next_Year[YTSData2016$E_Cig_Try_Next_Year == "3"] <- "No"
YTSData2016$E_Cig_Try_Next_Year[YTSData2016$E_Cig_Try_Next_Year == "4"] <- "No"

# Q7
YTSData2016$Cigarette_Ever_Used <- as.character(YTSData2016$Cigarette_Ever_Used)
YTSData2016$Cigarette_Ever_Used[YTSData2016$Cigarette_Ever_Used == "1"] <- "Yes"
YTSData2016$Cigarette_Ever_Used[YTSData2016$Cigarette_Ever_Used == "2"] <- "No"

# Q13 Valid numbers do not need to change
YTSData2016$Cigarette_Days_Used <- as.character(YTSData2016$Cigarette_Days_Used)

#Q15
YTSData2016$Cigarette_Last_Used <- as.character(YTSData2016$Cigarette_Last_Used)
YTSData2016$Cigarette_Last_Used[YTSData2016$Cigarette_Last_Used == "1"]<-"Today"
YTSData2016$Cigarette_Last_Used[YTSData2016$Cigarette_Last_Used == "2"]<-"Last 7 Days"
YTSData2016$Cigarette_Last_Usedd[YTSData2016$Cigarette_Last_Used == "3"]<-"Last Month"
YTSData2016$Cigarette_Last_Used[YTSData2016$Cigarette_Last_Used == "4"]<-"Last 6 Months"
YTSData2016$Cigarette_Last_Used[YTSData2016$Cigarette_Last_Used == "5"]<-"Last Year"
YTSData2016$Cigarette_Last_Used[YTSData2016$Cigarette_Last_Used == "6"]<-"1-4 Years Ago"
YTSData2016$Cigarette_Last_Used[YTSData2016$Cigarette_Last_Used == "7"]<-"5 Years Ago"

# Q6
YTSData2016$Cigarette_Curiosity <- as.character(YTSData2016$Cigarette_Curiosity)
YTSData2016$Cigarette_Curiosity[YTSData2016$Cigarette_Curiosity == "1"] <- "Yes"
YTSData2016$Cigarette_Curiosity[YTSData2016$Cigarette_Curiosity == "2"] <- "Yes"
YTSData2016$Cigarette_Curiosity[YTSData2016$Cigarette_Curiosity == "3"] <- "No"
YTSData2016$Cigarette_Curiosity[YTSData2016$Cigarette_Curiosity == "4"] <- "No"

# Q28
YTSData2016$Cigarette_Try_Next_Year <- as.character(YTSData2016$Cigarette_Try_Next_Year)
YTSData2016$Cigarette_Try_Next_Year[YTSData2016$Cigarette_Try_Next_Year == "1"] <- "Yes"
YTSData2016$Cigarette_Try_Next_Year[YTSData2016$Cigarette_Try_Next_Year == "2"] <- "Yes"
YTSData2016$Cigarette_Try_Next_Year[YTSData2016$Cigarette_Try_Next_Year == "3"] <- "No"
YTSData2016$Cigarette_Try_Next_Year[YTSData2016$Cigarette_Try_Next_Year  == "4"] <- "No"

# Q82
YTSData2016$The_Real_Cost <- as.character(YTSData2016$The_Real_Cost)
YTSData2016$The_Real_Cost[YTSData2016$The_Real_Cost == "1"] <- "Yes"
YTSData2016$The_Real_Cost[YTSData2016$The_Real_Cost == "2"] <- "No"
YTSData2016$The_Real_Cost[YTSData2016$The_Real_Cost == "3"] <- "Not sure"

# Q73
YTSData2016$E_Cig_Promotions_Internet <- as.character(YTSData2016$E_Cig_Promotions_Internet)
YTSData2016$E_Cig_Promotions_Internet[YTSData2016$E_Cig_Promotions_Internet == "1"] <- "I do not use the internet"
YTSData2016$E_Cig_Promotions_Internet[YTSData2016$E_Cig_Promotions_Internet == "2"] <- "Never"
YTSData2016$E_Cig_Promotions_Internet[YTSData2016$E_Cig_Promotions_Internet == "3"] <- "Rarely"
YTSData2016$E_Cig_Promotions_Internet[YTSData2016$E_Cig_Promotions_Internet == "4"] <- "Sometimes"
YTSData2016$E_Cig_Promotions_Internet[YTSData2016$E_Cig_Promotions_Internet == "5"] <- "Most of the time"
YTSData2016$E_Cig_Promotions_Internet[YTSData2016$E_Cig_Promotions_Internet == "6"] <- "Always"

# Q74
YTSData2016$Tobacco_Promotions_Internet <- as.character(YTSData2016$Tobacco_Promotions_Internet)
YTSData2016$Tobacco_Promotions_Internet[YTSData2016$Tobacco_Promotions_Internet == "1"] <- "I do not use the internet"
YTSData2016$Tobacco_Promotions_Internet[YTSData2016$Tobacco_Promotions_Internet == "2"] <- "Never"
YTSData2016$Tobacco_Promotions_Internet[YTSData2016$Tobacco_Promotions_Internet == "3"] <- "Rarely"
YTSData2016$Tobacco_Promotions_Internet[YTSData2016$Tobacco_Promotions_Internet == "4"] <- "Sometimes"
YTSData2016$Tobacco_Promotions_Internet[YTSData2016$Tobacco_Promotions_Internet == "5"] <- "Most of the time"
YTSData2016$Tobacco_Promotions_Internet[YTSData2016$Tobacco_Promotions_Internet == "6"] <- "Always"
```

\`\`\`{r move Dataset} write.csv(YTSData2016, file = "NYTSData2016.csv")
