---
title: "CleaningData2021"
format: html
editor: visual
---

```{r library}
library(dplyr)
library(ggplot2)
library(readr)
```

```{r setup}
getwd()
YTSData2021 <- read.csv("OG_nyts2020.csv")
```

```{r renamecol}
#first select columns to keep
YTSData <- YTSData %>% 
  select("QN2", "QN3", "QN6","QN9", "QN10", "QN29", "QN30", "QN31", "QN35", "QN38", "QN47", "QN48", "QN49", "QN109", "QN90", "QN92", "QN122", "QN128", "QN139")

YTSData2021 <- nyts2021 %>%
  rename(
        Gender <- QN2,
        Grade_of_Student <- QN3,
        E-Cig_Ever_Used <- QN6,
        E-Cig_Days_Used <- QN9,
        E-Cig_Last_Used <- QN10,
        E-Cig_Curiousity <- QN29,
        E-Cig_Try <- QN30,
        E_Cig_Try_Next_Year <- QN31,
        Cigarette_Ever_Used <- QN35,
        Cigarette_Days_Used <- QN38,
        Cigarette_Curiosity <- QN47,
        Cigarette_Try <- QN48,
        Cigarette_Try_Next_Year <- QN49,
        The_Real_Cost <- QN109,
        Any_Tobacco_Craving <- QN90,
        Attempt_Quitting_Tobacco <- QN92,
        Are_Tobacco_Products_Harmful <- QN122,
        E-Cig_Promotions_Internet <- QN128,
        Tobacco_Promotions_Internet <- QN139,
      )
```

```{r Duplicating and saving new dataset}
YTSDataNumbers <- YTSData
write.csv(YTSDataNumbers, file = "NYTS2021DataNumbers.csv")
```

```{r clean values}
# QN2
YTSData$Gender <- as.character(YTSData$Gender)

YTSData$Gender[YTSData$Gender == "1"] <- "M"
YTSData$Gender[YTSData$Gender == "2"] <- "F"

# QN3
YTSData$Grade_of_Student <- as.character(YTSData$Grade_of_Student)

YTSData$Grade_of_Student[YTSData$Grade_of_Student == "1"] <- "6th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "2"] <- "7th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "3"] <- "8th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "4"] <- "9th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "5"] <- "10th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "6"] <- "11th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "7"] <- "12th"
YTSData$Grade_of_Student[YTSData$Grade_of_Student == "8"] <- "Unplaced"

# QN6
YTSData$E_Cig_Ever_Used <- as.character(YTSData$E_Cig_Ever_Used)

YTSData$E_Cig_Ever_Used[YTSData$E_Cig_Ever_Used == "1"] <- "Yes"
YTSData$E_Cig_Ever_Used[YTSData$E_Cig_Ever_Used == "2"] <- "No"

# QN9
YTSData$E_Cig_Days_Used <- as.character(YTSData$E_Cig_Days_Used)
YTSData$E_Cig_Days_Used[YTSData$E_Cig_Days_Used == "1"] == "1"
YTSData$E_Cig_Days_Used[YTSData$E_Cig_Days_Used == "2"] == "5"
YTSData$E_Cig_Days_Used[YTSData$E_Cig_Days_Used == "3"] == "15"
YTSData$E_Cig_Days_Used[YTSData$E_Cig_Days_Used == "4"] == "35"
YTSData$E_Cig_Days_Used[YTSData$E_Cig_Days_Used == "5"] == "75"
YTSData$E_Cig_Days_Used[YTSData$E_Cig_Days_Used == "6"] == "100"

# QN10
YTSData$E_Cig_Last_Used <- as.character(YTSData$E_Cig_Last_Used)
#leave the numberical values alone

# QN29
YTSData$E_Cig_Curiousity <- as.character(YTSData$E_Cig_Curiousity)

YTSData$E_Cig_Curiousity[YTSData$E_Cig_Curiousity == "1"] <- "Yes"
YTSData$E_Cig_Curiousity[YTSData$E_Cig_Curiousity == "2"] <- "Yes"
YTSData$E_Cig_Curiousity[YTSData$E_Cig_Curiousity == "3"] <- "No"
YTSData$E_Cig_Curiousity[YTSData$E_Cig_Curiousity == "4"] <- "No"

# QN30
YTSData$E_Cig_Try <- as.character(YTSData$E_Cig_Try)
YTSData$E_Cig_Try[YTSData$E_Cig_Try == "1"] <- "Yes"
YTSData$E_Cig_Try[YTSData$E_Cig_Try == "2"] <- "Yes"
YTSData$E_Cig_Try[YTSData$E_Cig_Try == "3"] <- "No"
YTSData$E_Cig_Try[YTSData$E_Cig_Try == "4"] <- "No"

# QN31
YTSData$E_Cig_Try_Next_Year <- as.character(YTSData$E_Cig_Try_Next_Year)
YTSData$E_Cig_Try_Next_Year[YTSData$E_Cig_Try_Next_Year == "1"] <- "Yes"
YTSData$E_Cig_Try_Next_Year[YTSData$E_Cig_Try_Next_Year == "2"] <- "Yes"
YTSData$E_Cig_Try_Next_Year[YTSData$E_Cig_Try_Next_Year == "3"] <- "No"
YTSData$E_Cig_Try_Next_Year[YTSData$E_Cig_Try_Next_Year == "4"] <- "No"

# QN35
YTSData$Cigarette_Ever_Used <- as.character(YTSData$Cigarette_Ever_Used)
YTSData$Cigarette_Ever_Used[YTSData$Cigarette_Ever_Used == "1"] <- "Yes"
YTSData$Cigarette_Ever_Used[YTSData$Cigarette_Ever_Used == "2"] <- "No"

# QN25 Valid numbers do not need to change
#YTSData$Cigarette_Days_Used <- as.character(YTSData$Cigarette_Days_Used) 

# QN 47
YTSData$Cigarette_Curiosity <- as.character(YTSData$Cigarette_Curiosity)
YTSData$Cigarette_Curiosity[YTSData$Cigarette_Curiosity == "1"] <- "Yes"
YTSData$Cigarette_Curiosity[YTSData$Cigarette_Curiosity == "2"] <- "Yes"
YTSData$Cigarette_Curiosity[YTSData$Cigarette_Curiosity == "3"] <- "No"
YTSData$Cigarette_Curiosity[YTSData$Cigarette_Curiosity == "4"] <- "No"

# QN48
YTSData$Cigarette_Try <- as.character(YTSData$Cigarette_Try)
YTSData$Cigarette_Try[YTSData$Cigarette_Try == "1"] <- "Yes"
YTSData$Cigarette_Try[YTSData$Cigarette_Try == "2"] <- "Yes"
YTSData$Cigarette_Try[YTSData$Cigarette_Try == "3"] <- "No"
YTSData$Cigarette_Try[YTSData$Cigarette_Try  == "4"] <- "No"

# QN49
YTSData$Cigarette_Try_Next_Year <- as.character(YTSData$Cigarette_Try_Next_Year)
YTSData$Cigarette_Try_Next_Year[YTSData$Cigarette_Try_Next_Year == "1"] <- "Yes"
YTSData$Cigarette_Try_Next_Year[YTSData$Cigarette_Try_Next_Year == "2"] <- "Yes"
YTSData$Cigarette_Try_Next_Year[YTSData$Cigarette_Try_Next_Year == "3"] <- "No"
YTSData$Cigarette_Try_Next_Year[YTSData$Cigarette_Try_Next_Year  == "4"] <- "No"

# QN109
YTSData$The_Real_Cost <- as.character(YTSData$The_Real_Cost)
YTSData$The_Real_Cost[YTSData$The_Real_Cost == "1"] <- "Yes"
YTSData$The_Real_Cost[YTSData$The_Real_Cost == "2"] <- "No"
YTSData$The_Real_Cost[YTSData$The_Real_Cost == "3"] <- "Not sure"

# QN90
YTSData$Any_Tobacco_Craving <- as.character(YTSData$Any_Tobacco_Craving)
YTSData$Any_Tobacco_Craving[YTSData$Any_Tobacco_Craving == "1"] <- "Yes"
YTSData$Any_Tobacco_Craving[YTSData$Any_Tobacco_Craving == "2"] <- "No"

# QN92
YTSData$Attempt_Quitting_Tobacco <- as.character(YTSData$Attempt_Quitting_Tobacco)
YTSData$Attempt_Quitting_Tobacco[YTSData$Attempt_Quitting_Tobacco == "1"] <- "Yes"
YTSData$Attempt_Quitting_Tobacco[YTSData$Attempt_Quitting_Tobacco == "2"] <- "Yes"
YTSData$Attempt_Quitting_Tobacco[YTSData$Attempt_Quitting_Tobacco == "3"] <- "Yes"
YTSData$Attempt_Quitting_Tobacco[YTSData$Attempt_Quitting_Tobacco == "4"] <- "Yes"
YTSData$Attempt_Quitting_Tobacco[YTSData$Attempt_Quitting_Tobacco == "5"] <- "No"

# QN122
YTSData$Are_Tobacco_Products_Harmful <- as.character(YTSData$Are_Tobacco_Products_Harmful)
YTSData$Are_Tobacco_Products_Harmful[YTSData$Are_Tobacco_Products_Harmful == "1"] <- "Yes"
YTSData$Are_Tobacco_Products_Harmful[YTSData$Are_Tobacco_Products_Harmful == "2"] <- "Yes"
YTSData$Are_Tobacco_Products_Harmful[YTSData$Are_Tobacco_Products_Harmful == "3"] <- "No"
YTSData$Are_Tobacco_Products_Harmful[YTSData$Are_Tobacco_Products_Harmful == "4"] <- "No"

# QN128
YTSData$E_Cig_Promotions_Internet <- as.character(YTSData$E_Cig_Promotions_Internet)
YTSData$E_Cig_Promotions_Internet[YTSData$E_Cig_Promotions_Internet == "1"] <- "I do not use the internet"
YTSData$E_Cig_Promotions_Internet[YTSData$E_Cig_Promotions_Internet == "2"] <- "Never"
YTSData$E_Cig_Promotions_Internet[YTSData$E_Cig_Promotions_Internet == "3"] <- "Rarely"
YTSData$E_Cig_Promotions_Internet[YTSData$E_Cig_Promotions_Internet == "4"] <- "Sometimes"
YTSData$E_Cig_Promotions_Internet[YTSData$E_Cig_Promotions_Internet == "5"] <- "Most of the time"
YTSData$E_Cig_Promotions_Internet[YTSData$E_Cig_Promotions_Internet == "6"] <- "Always"

# QN139
YTSData$Tobacco_Promotions_Internet <- as.character(YTSData$Tobacco_Promotions_Internet)
YTSData$Tobacco_Promotions_Internet[YTSData$Tobacco_Promotions_Internet == "1"] <- "I do not use the internet"
YTSData$Tobacco_Promotions_Internet[YTSData$Tobacco_Promotions_Internet == "2"] <- "Never"
YTSData$Tobacco_Promotions_Internet[YTSData$Tobacco_Promotions_Internet == "3"] <- "Rarely"
YTSData$Tobacco_Promotions_Internet[YTSData$Tobacco_Promotions_Internet == "4"] <- "Sometimes"
YTSData$Tobacco_Promotions_Internet[YTSData$Tobacco_Promotions_Internet == "5"] <- "Most of the time"
YTSData$Tobacco_Promotions_Internet[YTSData$Tobacco_Promotions_Internet == "6"] <- "Always"
```

```{r move Dataset}
write.csv(YTSData, file = "NYTSData2021.csv")
```
